List<String> brand = [ "Maruti Suzuki",
  "Hyundai",
  "Mahindra",
  "Toyota",
  "Honda",
  "Tata",
  "Frod",
  "Volkswagen",
  "Renault",
  'Mercedes-Benz','BMW','Chevrolet','Kia','Skoda','Nissan','Audi','Jeep','MG','Land Rover','Datsun','Volvo','Fiat','Jaguar','Mitsubishi','Mini','Porsche','Force Motors','Isuzu','Bajaj','Ambassador','Lexus','Bajaj','Mahindra Renault','Bentley','Ssangyong','Lamborghini','Ashok Leyland','Premier','Ferrari','Rolls-Royce','Maserati','Dc','Hummer','Aston Martin','Eicher Polaris','Opel','Ashok','Mazda','ICML','Daewoo','Bugatti','Cadillac','Chrysler','Lotus','Maybach','Citroen','Tesla','Hindustan Motors'];


/*
List<String> model = [
  "Maruti Suzuki": ["Swift", "Baleno", "Alto 800", "Wagon R", "Dzire", "Ciaz", "Ertiga", "XL6", "Vitara Brezza", "Grand Vitara"],
];*/

const Map<String, List<String>> states = {
  "Maruti Suzuki": ["Swift", "Baleno", "Alto 800", "Wagon R", "Dzire", "Ciaz", "Ertiga", "XL6", "Vitara Brezza", "Grand Vitara"],
  "Hyundai": ["i20", "Creta", "Verna", "Venue", "Tucson", "Aura", "Santro"],
  "Mahindra": ["Thar", "Scorpio N", "XUV700", "Bolero", "XUV300", "Marazzo"],
  "Toyota": ["Fortuner", "Innova Crysta", "Urban Cruiser Hyryder", "Camry", "Hilux", "Glanza"],
  "Honda": ["City", "Amaze", "WR-V", "Jazz", "BR-V", "Civic"],
  "Tata": ["Nexon", "Harrier", "Safari", "Altroz", "Tiago", "Tigor", "Hexa", "Zest"],
  "Ford": ["EcoSport", "Endeavour", "Figo", "Freestyle", "Fiesta", "Mustang"],
  "Volkswagen": ["Polo", "Vento","Tiguan", "Passat", "Jetta", "Taigun"],
  "Renault": ["Kwid", "Duster", "Triber", "Lodgy", "Captur", "Koleos"]

};


List<String> bikeBrands = [
  "Hero",
  "Honda",
  "Bajaj",
  "TVS",
  "Royal Enfield",
  "Yamaha",
  "Suzuki",
  "KTM",
  "Harley-Davidson",
  "Ducati",
  "BMW Motorrad",
  "Triumph",
  "Jawa",
  "Benelli",
  "Mahindra",
  "Aprilia",
  "Moto Guzzi",
  "Indian Motorcycle",
  "MV Agusta",
  "Husqvarna",
  "Lifan",
  "Keeway",
  "CFMoto",
  "UM Motorcycles",
  "Kawasaki",
  "Zontes",
  "Vespa",
  "Lambretta",
  "Yezdi",
  "Norton",
  "Bimota",
  "SWM",
  "Ather Energy",
  "Revolt Motors",
  "Ultraviolette",
  "Okinawa",
  "Ampere",
  "Pure EV",
  "Tork Motors"
];
List<String> smartphoneBrands = [
  "Apple",
  "Samsung",
  "Google",
  "OnePlus",
  "Xiaomi",
  "Realme",
  "Oppo",
  "Vivo",
  "Motorola",
  "Nothing",
  "Asus ROG",
  "Sony Xperia",
  "RedMagic",
  "Black Shark",
  "Huawei",
  "Honor",
  "Infinix",
  "Tecno",
  "iQOO",
  "Lava",
  "Micromax",
  "Itel",
  "Nokia",
  "Meizu",
  "ZTE",
  "Lenovo",
  "HTC",
  "Fairphone",
  "TCL",
  "Sharp",
  "Gionee",
  "Coolpad",
  "Essential",
  "Alcatel",
  "BLU",
  "LeEco",
  "Panasonic",
  "Poco",
  "Karbonn",
  "Celkon"
];


List<String> tabletBrands = [
  "Apple iPad",
  "Samsung Galaxy Tab",
  "Microsoft Surface",
  "Lenovo Tab",
  "Huawei MatePad",
  "Amazon Fire Tablet",
  "Google Pixel Tablet",
  "Xiaomi Pad",
  "Realme Pad",
  "Oppo Pad",
  "Vivo Pad",
  "Nokia Tablet",
  "Asus ZenPad",
  "Honor Pad",
  "TCL Tab",
  "Acer Iconia",
  "Dell Venue",
  "Sony Xperia Tablet",
  "LG G Pad",
  "Panasonic Toughpad",
  "Alcatel Tablet",
  "HP ElitePad",
  "HTC Tablet",
  "Chuwi Tablet",
  "Teclast Tablet",
  "Fusion5 Tablet"
];
