name: Build and Deploy Flutter Web App 

on:
  push:
    branches: ["main"] 

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Enable Flutter Web
        run: flutter config --enable-web

      - name: Clean Flutter project
        run: flutter clean

      - name: Install dependencies
        run: flutter pub get

      - name: Build Flutter Web
        run: flutter build web --dart-define=FLUTTER_WEB_USE_SKIA=true
